import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { FaGraduationCap } from "react-icons/fa6";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        
     <header className="navbar" >
     {/* logo */}

      <div>
      <h2 className="logo" ><FaGraduationCap /></h2>
      </div>

         {/* {buttons link} */}
         <div>
         <nav>
         <ul className="nav-links">
         <li><Link href={"/"}>Welcome</Link></li>
         <li ><Link href={"/about"}>About US</Link></li>
         <li ><Link href={"/contact"}>Contact Us</Link></li>
         </ul>
         </nav>
         </div>
         </header>


        {children}
      </body>
    </html>
  );
}
